### ISSUE TITLE
markdown redcarpet

### ISSUE THREAD

**Issue by icusick** [icusick/buffy#3]
i've installed the redcarpet and required it in my config page and now i have no idea what to do next. i've read some stuff online and i think there's going to be something like 

```
Redcarpet::Markdown.new
```

and it's going to go in the new and edit forms...but where? how? i'm very unclear on how this will fit in. right now, when you go to the "make a new article" page there are about 8 different input boxes that each correspond with a different part of the article table: 

```
<form method="POST" action="/articles" >
    <input type="text" name="title" placeholder="title">
    <input type="text" name="plot" placeholder="plot">
    <input type="text" name="bio" placeholder="bio">
    <input type="text" name="antagonist" placeholder="antagonist">
    <input type="text" name="special_powers" placeholder="special powers">
    <input type="text" name="minions" placeholder="minions">
    <input type="text" name="buffy_quarrel" placeholder="buffy quarrel">
    <input type="text" name="demise" placeholder="demise">
    <input type="text" name="category_id" placeholder="category id">
    <button>Submit Article</button>
</form>
```

as i understand it, this will change it to make it look like:

```
## Title

##Plot

##Bio
```

so that you can fill out something that looks like a page as opposed to fill in all the little boxes. i've tried:

```
<form method="POST" action="/articles" >
    Redcarpet::Markdown.new(
        <input type="text" name="title" placeholder="title">
    <input type="text" name="plot" placeholder="plot">
    <input type="text" name="bio" placeholder="bio">
    <input type="text" name="antagonist" placeholder="antagonist">
    <input type="text" name="special_powers" placeholder="special powers">
    <input type="text" name="minions" placeholder="minions">
    <input type="text" name="buffy_quarrel" placeholder="buffy quarrel">
    <input type="text" name="demise" placeholder="demise">
    <input type="text" name="category_id" placeholder="category id">)
    <button>Submit Article</button>
</form>
```

but that hasn't done anything. that's the only idea i have. i'm very confused.

**Comment by phlco** [comment]
Break up your thinking a little bit there.

Have a look at https://gist.github.com/ 

You can enter "markdown" in a form field. And then later when viewing the page, that information should be rendered as HTML. But if you were to click "edit" and change the content you'd be changing the underlying markdown text.

So allow your users to input text into your input fields. Take a look at mdn's docs for textarea if you want to add more than a line of text.  Then store that information in your database. Later when you want to view it try rendering it with the markdown viewer first. It just turns a string into html, so apply that in your route handler and then show it in your view.

Make sense?
